config/routes.rb
Rails.application.routes.draw do
  root 'zoos#index'

  resources :zoos, except: [:show] do
    resources :animals
    resources :lions, controller: 'animals', type: 'Lion'
    resources :bears, controller: 'animals', type: 'Bear'
    resources :elephants, controller: 'animals', type: 'Elephant'
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  belongs_to :zoo
  self.inheritance_column = :race
  validates_presence_of :name

  def self.races
    %w(Lion Bear Elephant)
  end

  #scopes
  def self.lions
    where(race: 'Lion')
  end

  def self.bears
    where(race: 'Bear')
  end

  def self.elephants
    where(race: 'Elephant')
  end

  def talk
    raise "You need to override this method in your sub class"
  end

end

app/models/bear.rb
class Bear < Animal
  def talk
    "GRRRR!!!"
  end
end

app/models/elephant.rb
class Elephant < Animal
  def talk
    "BVOOOOOOOoOOOooooOOOOOO"
  end
end

app/models/lion.rb
class Lion < Animal
  def talk
    "Rawr!"
  end
end

app/models/zoo.rb
class Zoo < ActiveRecord::Base
  has_many :animals, dependent: :destroy
  delegate :lions, :bears, :elephants, to: :animals
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  include StiHelper

  before_action :set_race
  before_action :set_zoo
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  def index
    @animals = params[:type] ? @zoo.animals.where(race: race_class) : @zoo.animals.all
  end

  def show
  end

  def new
    @animal = race_class.new
  end

  def edit
  end

  def create
    @animal = @zoo.animals.new(animal_params)
    if @animal.save
      redirect_to sti_animal_path(@zoo), notice: "#{race} was created"
    else
      render :new
    end
  end

  def update
    if @animal.update(animal_params)
      redirect_to sti_animal_path(@zoo), notice: "#{race} was updated"
    else
      render :edit
    end
  end

  def destroy
    @animal.destroy
    redirect_to sti_animal_path(@zoo)
  end

  private
    def set_zoo
      @zoo = Zoo.find(params[:zoo_id])
    end

    def set_race
      @race = race
    end

    def race
      Animal.races.include?(params[:type]) ? params[:type] : "Animal"
    end

    def set_animal
      @animal = race_class.find(params[:id])
    end

    def race_class
      race.constantize
    end

    def animal_params
      params.require(race.underscore.to_sym).permit(:name, :race, :age)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/zoos_controller.rb
class ZoosController < ApplicationController
  before_action :zoo, except: [:index, :new, :create]

  def index
    @zoos = Zoo.all
  end

  def show
  end

  def new
    @zoo = Zoo.new
  end

  def edit
  end

  def create
    @zoo = Zoo.new(zoo_params)
    if @zoo.save
      redirect_to zoos_path
    else
      render :new
    end
  end

  def update
    if @zoo.update(zoo_params)
      redirect_to zoos_path
    else
      render :edit
    end
  end

  def destroy
    @zoo.destroy
    redirect_to zoos_path
  end

  private
    def zoo_params
      params.require(:zoo).permit(:name)
    end

    def zoo
      @zoo = Zoo.find(params[:id])
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sti_helper.rb
module StiHelper
  def sti_animal_path(zoo, race = "animal", animal = nil, action = nil)
    send "#{format_sti(action, race, animal)}_path", zoo, animal
  end

  def format_sti(action, race, animal)
    action || animal ?
      "#{format_action(action)}#{race.underscore}" :
      "zoo_#{race.underscore.pluralize}"
  end

  def format_action(action)
    action ? "#{action}_zoo_" : "zoo_"
  end
end

app/helpers/zoos_helper.rb
module ZoosHelper
end

app/views/animals/_form.html.erb
<%= form_for [@zoo, @animal] do |f| %>
  <div class="field">
    <%= f.label :name %>
    <br />
    <%= f.text_field :name, required: :true %>
    <br />
  </div>

  <div class="field">
    <%= f.label :race %>
    <br />
    <% if  @race != "Animal" %>
      <p><%= @race %></p>
      <%= f.hidden_field :race %>
    <% else %>
      <%= f.select :race, Animal.races %>
    <% end %>
    <br />
  </div>

  <div class="field">
    <%= f.label :age %>
    <br />
    <%= f.text_field :age %>
    <br />
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', sti_animal_path(@zoo) %>

app/views/animals/edit.html.erb
<h1> Editing <%= @race %> </h1>
<%= render partial: 'form' %>

app/views/animals/index.html.erb
<h1>
  Viewing All <%= @race.pluralize %> In Zoo: <%= @zoo.name %>
</h1>
<% if @animals.any? %>
  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Race</th>
        <th>Age</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @animals.each do |animal| %>
        <tr>
          <td>
            <%= animal.name %>
          </td>
          <td>
            <%= animal.race %>
          </td>
          <td>
            <%= animal.age %>
          </td>
          <% unless params[:type] %>
            <td>
              <%= link_to "See all #{animal.race.pluralize}", sti_animal_path(@zoo, animal.race) %>
            </td>
          <% end %>
          <td>
            <%= link_to 'Show', sti_animal_path(@zoo, animal.race, animal) %>
          </td>
          <td>
            <%= link_to 'Edit', sti_animal_path(@zoo, animal.race, animal, :edit) %>
          </td>
          <td>
            <%= link_to 'Destroy', sti_animal_path(@zoo, animal.race, animal), method: :delete, data: {confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h3>No Zoo Animals To Display</h3>
<% end %>
<%= link_to "New #{@race}", sti_animal_path(@zoo, @race, nil, :new) %>
<br/>
<% if params[:type] %>
  <%= link_to 'See all zoo animals', sti_animal_path(@zoo) %>
<% end %>
<hr/>
<%= link_to 'All Zoos', zoos_path %>

app/views/animals/new.html.erb
<h1>
  New <%= @race.capitalize %> In Zoo: <%= @zoo.name %>
</h1>

<%= render partial: 'form' %>

app/views/animals/show.html.erb
<h1>
  Hi, I am a <%= @animal.race %>
</h1>
<p>
  My name is <%= @animal.name %>
</p>
<%= @animal.talk %>
<br />
<%= link_to 'Back', sti_animal_path(@zoo) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StiZoo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zoos/_form.html.erb
<%= form_for @zoo do |f| %>
  <%= f.text_field :name, required: true, placeholder: 'Zoo Name' %>
  <%= f.submit %>
<% end %>

app/views/zoos/edit.html.erb
<h1>Editing Zoo: <%= @zoo.name %></h1>
<%= render partial: 'form' %>

app/views/zoos/index.html.erb
<h1>Zoos</h1>
<hr />
<% if @zoos.any? %>
  <ul>
    <% @zoos.each do |zoo| %>
      <li>
        <%= link_to zoo.name.titleize, sti_animal_path(zoo) %>
        |
        <%= link_to 'Edit', edit_zoo_path(zoo) %>
        |
        <%= link_to 'Delete', zoo_path(zoo), method: :delete, data: {confirm: 'Really Delete?'} %>
      </li>
    <% end %>
  </ul>
<% else %>
 <h3>No Zoos</h3>
<% end %>
<br />
<%= link_to 'Create New Zoo', new_zoo_path %>

app/views/zoos/new.html.erb
<h1>New Zoo</h1>
<%= render partial: 'form' %>

app/views/zoos/show.html.erb
<h1>Zoos#show</h1>
<p>Find me in app/views/zoos/show.html.erb</p>